export const CategoryTypes = {
  ITEM_CATEGORY_FETCH_START: "ITEM_CATEGORY_FETCH_START",
  ITEM_CATEGORY_FETCH_DONE: "ITEM_CATEGORY_FETCH_DONE",
  ITEM_CATEGORY_FETCH_ERROR: "ITEM_CATEGORY_FETCH_ERROR",
};
